### ISSUE TITLE
Videos not playing after a day 5/18

### ISSUE THREAD

**Issue by IJ08** [Twoure/9anime.bundle#10]
Hi again.

VIdeos were working until yesterday. I already did the fix for deleting DATAHTTP cache  but still not working RE: https://github.com/Twoure/9anime.bundle/issues/8 

Please find updated logs
[LOGS.zip](https://github.com/Twoure/9anime.bundle/files/1012433/LOGS.zip)

**Comment by Twoure** [comment]
https://github.com/Twoure/9anime.bundle/issues/9#issuecomment-302435325

**Comment by IJ08** [comment]
Thanks, Subscribing to the thread

**Comment by Twoure** [comment]
Fixed in https://github.com/Twoure/9anime.bundle/commit/fb08f54b14ec099795c6d2deced960705251febb
