### ISSUE TITLE
Not playing 5/24 

### ISSUE THREAD

**Issue by IJ08** [Twoure/9anime.bundle#13]
[LOGS.zip](https://github.com/Twoure/9anime.bundle/files/1027353/LOGS.zip)

Vids not playing. Already tried restarting PMS, server and resetting DATAHTTP cache.

The weird thing is, I was testing it for several videos from recent updates and SAKURA QUEST was working fine but the rest isn't. I also tried a video I just watched yesterday same episode after making sure SAKURA QUEST was working and that video failed to play now.

I got it captured both in attached logs. Thanks!

**Comment by IJ08** [comment]
[LOGS.zip](https://github.com/Twoure/9anime.bundle/files/1028718/LOGS.zip)

Uploading a new set of logs as I noticed that now all videos are showing "CHANNEL NOT RESPONDING"

**Comment by Twoure** [comment]
Refer to:
- https://twitter.com/9animeto/status/867396808246308864
- https://www.reddit.com/r/9anime/comments/6d6k1l/9anime_is_currently_down/

**Comment by IJ08** [comment]
Thanks don't have twitter so that's why LOL. Will monitor

**Comment by IJ08** [comment]
Closing, checked and 9anime channel is working again
