### ISSUE TITLE
My channel hasnt worked for weeks

### ISSUE THREAD

**Issue by Khriss17** [Twoure/9anime.bundle#16]
For the last couple of weeks, I haven't been able to get 9anime to work. I have both Node nd Java 8 SDK downloaded and I also tried deleting my DataHTTP folder and nothing has worked for me. I even went as far as to deleting everything related 9anime from my computer and reinstalling it but that didn't work either. I don't know what else to do.

9anime log
https://pastebin.com/ePkFMWiV

System log
https://pastebin.com/AQktKFqE

**Comment by Twoure** [comment]
Pushed a fix today in the [dev](https://github.com/Twoure/9anime.bundle/tree/dev) branch.
Try downloading and installing the `dev` branch, then restarting PMS.

**Comment by Twoure** [comment]
> For the last couple of weeks, I haven't been able to get 9anime to work.

FYI: https://github.com/Twoure/9anime.bundle/issues/15#issuecomment-306004794 was probably the root of your original issue.

**Comment by Khriss17** [comment]
The new update is working, thank you
