### ISSUE TITLE
Issue playing videos 3/23

### ISSUE THREAD

**Issue by IJ08** [Twoure/9anime.bundle#3]
So just recently there was an issue playing videos via the PMS for this channel onto ROKU. I suspect that it is related to the changes plaguing kissanime networks as well...

Can you help check if it is indeed the case? I had this working yesterday.

**Comment by IJ08** [comment]
Adding logs

[Logs.zip](https://github.com/Twoure/9anime.bundle/files/869469/Logs.zip)

**Comment by Twoure** [comment]
Should be fixed in `dev` branch.  Let me know.

**Comment by Twoure** [comment]
Fixed in [v1.0.1](https://github.com/Twoure/9anime.bundle/releases/tag/v1.0.1).

**Comment by IJ08** [comment]
Uploading the logs, I tried dev and v1.0.1 not working both. 
[9anime log.zip](https://github.com/Twoure/9anime.bundle/files/998057/9anime.log.zip)
