### ISSUE TITLE
Videos still not playing as of 5/10

### ISSUE THREAD

**Issue by IJ08** [Twoure/9anime.bundle#8]
[9anime.log.zip](https://github.com/Twoure/9anime.bundle/files/1001741/9anime.log.zip)

**Comment by Twoure** [comment]
Download and install the latest `dev` branch, then restart PMS.  Looks like this is a JavaScript issue.  You'll either need NodeJS installed or Nashorn _(i.e. Java 8 SDK from Oracle)_.

**Comment by IJ08** [comment]
Okay, do I just need java8 or even Nashorn?

**Comment by Twoure** [comment]
> Okay, do I just need java8 or even Nashorn?

Either, Node.js OR Java 8.  Don't need both, and Nashorn is included with Java 8 SDK.

**Comment by IJ08** [comment]
Done. Now my plex isn't seeing the dev channel for 9anime. Restarted twice and it isn't there. 

I downloaded latest java8 from Oracle and dev branch per - https://github.com/Twoure/9anime.bundle/tree/dev

**Comment by IJ08** [comment]
Looks like it can't find the java - 
[LOGS.zip](https://github.com/Twoure/9anime.bundle/files/1002744/LOGS.zip)

**Comment by Twoure** [comment]
Thanks for the log file, looks like I made a syntax mistake. Pushed fix now. Download and install, then restart PMS.

**Comment by IJ08** [comment]
Hi @Twoure downloaded twice and restarted twice, still having same issue. Channel not showing up on PLEX. Looks like the same from logs

Updated logs - 
[LOGS.zip](https://github.com/Twoure/9anime.bundle/files/1002782/LOGS.zip)

**Comment by Twoure** [comment]
Took a longer look, and pushed another patch.  Please download and try again.  Thanks for debugging with me.

**Comment by IJ08** [comment]
No problem, I should be thanking you. So the channel is showing up but videos aren't playing still. Tried several newest vids, 4 of them in the recent updates but not working. Logs - 
[LOGS.zip](https://github.com/Twoure/9anime.bundle/files/1002844/LOGS.zip)

**Comment by Twoure** [comment]
PyExecJS is not picking up your `Nashorn` install.  All it can see is your `JScript`.  Try opening a command prompt window and typing
```bash
jjs -v
```
It should print out the version of Nashorn you have installed and will enter into a shell session.
For example mine gives:
```bash
$> jjs -v
nashorn 1.8.0_131
jjs> quit()
```
To exit type:
```js
quit()
```
or
```js
exit()
```
If its not installed, then you may have to dig deeper into how-to install it properly.  Otherwise, you can always download and install Node.js as an alternative.  Basically either one needs to be accessible to all users, otherwise Plex will not be able to use the JRE.

**Comment by Twoure** [comment]
Sorry, to add, You'll need [Java 8 JDK](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html), which is the development kit giving access to Nashorn.

Links for either JREs:
- Nashorn: http://www.oracle.com/technetwork/articles/java/jf14-nashorn-2126515.html
- Node.js: https://nodejs.org

**Comment by IJ08** [comment]
Thanks @Twoure , I downloaded nodejs as it was pretty straightforward. I restarted and checked version. Still can't play video but logs have changed. Logs look like the same as well for the kissnetwork error.

Attached - 
[LOGS.zip](https://github.com/Twoure/9anime.bundle/files/1002916/LOGS.zip)

**Comment by Twoure** [comment]
This is due to a dirty cache.  Try deleting this channel's cache by deleting the `DataHTTP` folder located in
```
%LOCALAPPDATA%\Plex Media Server\Plug-in Support\Data\com.plexapp.plugins.9anime\DataItems\DataHTTP
```
If you delete the folder, then restart PMS, otherwise if you preserve the folder but delete it's contents, then you shouldn't need to restart PMS.

**Comment by IJ08** [comment]
Okay let me try that when I get home. If that's the solution, probably the same thing for the other channels then.  I will update you ASAP

**Comment by IJ08** [comment]
Wow. Okay it is indeed working now after clearing that up. What's the root cause? Will that happen again? Thanks as usual!

**Comment by Twoure** [comment]
> Wow. Okay it is indeed working now after clearing that up.

Glad to hear.

> What's the root cause?

An unexpected error occurred, and I don't have logic setup to NOT cache when an unexpected error happens.

> Will that happen again?

Possibly, but this is the `dev` branch so is expected to have bugs and such.  I'll work at better error handling so the stable release will benefit.

> Thanks as usual!

You're welcome :smile:.
